apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cica-case-review-documents-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: cica-case-review-documents-ingress-cica-review-case-documents-dev-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/affinity: cookie # forces cookie sessions to be "sticky" and always use the same pod.
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/whitelist-source-range: "213.107.167.128/32,35.176.93.186/32"

spec:
  ingressClassName: default
  tls:
    - hosts:
        - cica-review-case-documents-dev.apps.live.cloud-platform.service.justice.gov.uk
  rules:
    - host: cica-review-case-documents-dev.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: cica-case-review-documents-service # this should match the metadata.name in service.yml
                port:
                  number: 8080
